#!/usr/bin/env python3
# Auto-extracted from papers/fermi_survival_2025/paper.md
# Generated by SHELL paper pipeline
import os
os.makedirs('figures', exist_ok=True)

# Figure 3: E[T]_upper vs. Λ for different f_SETI values (application of Corollary 1)
import matplotlib.pyplot as plt
import numpy as np

alpha = 0.05
mu_upper = -np.log(alpha)
T_gal = 13.6e9

Lambda_vals = np.logspace(-5, 2, 1000)
f_SETI_values = [1e-8, 1e-7, 1e-6, 1e-5]
labels = [r'$f_{\rm SETI} = 10^{-8}$',
          r'$f_{\rm SETI} = 10^{-7}$ (baseline)',
          r'$f_{\rm SETI} = 10^{-6}$',
          r'$f_{\rm SETI} = 10^{-5}$']
colors = ['blue', 'black', 'red', 'darkgreen']
styles = ['--', '-', '-.', ':']

fig, ax = plt.subplots(1, 1, figsize=(8, 6))

for f_SETI, label, color, style in zip(f_SETI_values, labels, colors, styles):
    ET_upper = mu_upper / (f_SETI * Lambda_vals)
    ax.loglog(Lambda_vals, ET_upper, color=color, linestyle=style,
              linewidth=2, label=label)

ax.axhline(y=T_gal, color='gray', linestyle=':', linewidth=1,
           label=r'$T_{\rm gal} = 13.6$ Gyr')
ax.axhline(y=1e8, color='orange', linestyle=':', linewidth=0.7,
           label=r'$\tau = 10^8$ yr (complex life)')
ax.axhline(y=1e4, color='purple', linestyle=':', linewidth=0.7,
           label=r'$\tau = 10^4$ yr (civilization)')

ax.set_xlabel(r'Emergence rate $\Lambda$ [civ yr$^{-1}$]', fontsize=12)
ax.set_ylabel(r'$E[T]_{\rm upper}$ [yr]  (95% confidence)', fontsize=12)
ax.set_title(r'Upper bound on mean communicative lifetime from $N_{\rm det} = 0$'
             '\n' r'(Corollary 1, $\alpha = 0.05$)', fontsize=12)
ax.legend(fontsize=9, loc='upper right')
ax.set_xlim(1e-5, 1e2)
ax.set_ylim(1e2, 1e16)
plt.tight_layout()
plt.savefig('figures/figure_3.pdf', dpi=300, bbox_inches='tight')
