#!/usr/bin/env python3
# Auto-extracted from papers/fermi_survival_2025/paper.md
# Generated by SHELL paper pipeline
import os
os.makedirs('figures', exist_ok=True)

# Figure 4: Λ_crit(τ) threshold — regions where data force E[T] < τ (Theorem 5)
import matplotlib.pyplot as plt
import numpy as np

alpha = 0.05
mu_upper = -np.log(alpha)
f_SETI = 1e-7

tau_vals = np.logspace(3, 11, 1000)
Lambda_crit = mu_upper / (f_SETI * tau_vals)

fig, ax = plt.subplots(1, 1, figsize=(8, 6))

ax.loglog(tau_vals, Lambda_crit, 'k-', linewidth=2,
          label=r'$\Lambda_{\rm crit}(\tau) = -\ln\alpha\, /\, (f_{\rm SETI} \cdot \tau)$')
ax.fill_between(tau_vals, Lambda_crit, 1e6, alpha=0.15, color='red',
                label=r'$\Lambda > \Lambda_{\rm crit}$: $E[T] < \tau$ forced (late filter)')
ax.fill_between(tau_vals, 1e-10, Lambda_crit, alpha=0.15, color='blue',
                label=r'$\Lambda < \Lambda_{\rm crit}$: $E[T]$ unconstrained')

refs = [(1e4, 'Civilization'), (1e6, 'Geological'),
        (1e8, 'Complex life'), (1e10, 'Galactic')]
for tau_ref, name in refs:
    lc = mu_upper / (f_SETI * tau_ref)
    ax.plot(tau_ref, lc, 'ko', markersize=5)
    ax.annotate(name, (tau_ref, lc), textcoords="offset points",
                xytext=(10, 5), fontsize=9)

ax.set_xlabel(r'Reference timescale $\tau$ [yr]', fontsize=12)
ax.set_ylabel(r'Critical emergence rate $\Lambda_{\rm crit}$ [civ yr$^{-1}$]',
              fontsize=12)
ax.set_title(r'Filter location threshold (Theorem 5, $f_{\rm SETI} = 10^{-7}$, $\alpha = 0.05$)',
             fontsize=12)
ax.legend(fontsize=9, loc='upper right')
ax.set_xlim(1e3, 1e11)
ax.set_ylim(1e-10, 1e6)
plt.tight_layout()
plt.savefig('figures/figure_4.pdf', dpi=300, bbox_inches='tight')
