#!/usr/bin/env python3
# Auto-extracted from papers/fermi_survival_2025/paper.md
# Generated by SHELL paper pipeline
import os
os.makedirs('figures', exist_ok=True)

# Figure 2: Weibull survival functions for k = 0.5, 1.0, 2.0 at equal E[T]
import matplotlib.pyplot as plt
import numpy as np
from scipy.special import gamma

E_T = 1.0  # normalized mean lifetime

k_values = [0.5, 1.0, 2.0]
labels = [r'$k = 0.5$ (decreasing hazard — early filter)',
          r'$k = 1.0$ (constant hazard — exponential)',
          r'$k = 2.0$ (increasing hazard — late filter)']
colors = ['blue', 'black', 'red']
styles = ['--', '-', '-.']

t = np.linspace(0, 5 * E_T, 1000)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

# Panel A: Survival functions
for k, label, color, style in zip(k_values, labels, colors, styles):
    eta = E_T / gamma(1 + 1.0/k)
    S = np.exp(-(t / eta)**k)
    ax1.plot(t / E_T, S, color=color, linestyle=style, linewidth=2, label=label)

ax1.set_xlabel(r'$t\, /\, E[T]$', fontsize=12)
ax1.set_ylabel(r'$S(t)$', fontsize=12)
ax1.set_title('(a) Survival functions', fontsize=12)
ax1.legend(fontsize=9, loc='upper right')
ax1.set_xlim(0, 5)
ax1.set_ylim(0, 1.05)
ax1.axvline(x=1.0, color='gray', linestyle=':', linewidth=0.5)

# Panel B: Hazard functions
t_hz = np.linspace(0.01 * E_T, 5 * E_T, 1000)
for k, label, color, style in zip(k_values, labels, colors, styles):
    eta = E_T / gamma(1 + 1.0/k)
    h = (k / eta) * (t_hz / eta)**(k - 1)
    ax2.plot(t_hz / E_T, h * E_T, color=color, linestyle=style, linewidth=2,
             label=label)

ax2.set_xlabel(r'$t\, /\, E[T]$', fontsize=12)
ax2.set_ylabel(r'$h(t) \cdot E[T]$  (dimensionless)', fontsize=12)
ax2.set_title('(b) Hazard functions', fontsize=12)
ax2.legend(fontsize=9, loc='upper left')
ax2.set_xlim(0, 5)
ax2.set_ylim(0, 5)
ax2.axvline(x=1.0, color='gray', linestyle=':', linewidth=0.5)

plt.tight_layout()
plt.savefig('figures/figure_2.pdf', dpi=300, bbox_inches='tight')
