#!/usr/bin/env python3
# Auto-extracted from papers/fermi_survival_2025/paper.md
# Generated by SHELL paper pipeline
import os
os.makedirs('figures', exist_ok=True)

# Figure 1: Log-likelihood ℓ(λ) = −μ(λ) under exponential hazard model
import matplotlib.pyplot as plt
import numpy as np

f_SETI = 1e-7
Lambda = 1e-2  # emergence rate, civilizations per year
T_gal = 13.6e9  # years

lambda_vals = np.logspace(-12, -4, 1000)
mu_vals = f_SETI * Lambda * (1 - np.exp(-lambda_vals * T_gal)) / lambda_vals
ell_vals = -mu_vals

fig, ax = plt.subplots(1, 1, figsize=(8, 5))
ax.semilogx(lambda_vals, ell_vals, 'k-', linewidth=2)
ax.axhline(y=0, color='gray', linestyle='--', linewidth=0.5)
ax.axhline(y=-(-np.log(0.05)), color='red', linestyle='--', linewidth=1,
           label=r'$\ell = -\mu_{\rm upper}$ ($\alpha = 0.05$, $\mu_{\rm upper} \approx 3.0$)')
ax.set_xlabel(r'Hazard rate $\lambda$ [yr$^{-1}$]', fontsize=12)
ax.set_ylabel(r'Log-likelihood $\ell(\lambda)$', fontsize=12)
ax.set_title(r'Log-likelihood under exponential hazard, $N_{\rm det} = 0$'
             '\n' r'($f_{\rm SETI} = 10^{-7}$, $\Lambda = 10^{-2}$ yr$^{-1}$)',
             fontsize=12)
ax.legend(fontsize=10, loc='lower right')
ax.set_xlim(lambda_vals[0], lambda_vals[-1])
plt.tight_layout()
plt.savefig('figures/figure_1.pdf', dpi=300, bbox_inches='tight')
